# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Exclude Spree-generated files from style checks
AllCops:
  Exclude:
    - "db/migrate/*.spree.rb"
    - "config/initializers/spree.rb"
